AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ec2CloudFormerRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: ec2CloudFormerRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "ec2CloudFormer"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"
  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      InstanceProfileName: ec2CloudFormerRole
      Roles:
        -
          Ref: "ec2CloudFormerRole"
